### ISSUE TITLE
Multi-echo delay time

### ISSUE THREAD

**Issue by Aaronearlerichardson** [SIMEXP/Data2Bids#15]
Is there a specific format to the delayTimeInSec parameter if we have multi-echo data with multiple different delay times?

**Comment by ltetrel** [comment]
Hi, no there is no way to specify multiple delay times. I used this parameter [to create the nifti object](https://github.com/SIMEXP/Data2Bids/blob/7dcbd9b1bf02a748779c0d55000259f70e17ffe9/data2bids/data2bids.py#L155), you can have more information in [nibabel documentation](https://nipy.org/nibabel/nibabel_images.html#the-image-header).
